### ISSUE TITLE
FileNotFound error in python

### ISSUE THREAD

**Issue by fcoury** [adamws/keyboard-tools#15]
An unexpected error occurred. Please try again. If the error persists, you can submit the issue with the following details at GitHub:

Traceback (most recent call last):

File "/kicad/src/tasks.py", line 70, in generate_kicad_project

__upload_to_storage(task_id, log_path)

File "/kicad/src/tasks.py", line 57, in __upload_to_storage

client.fput_object(

File "/kicad/.local/lib/python3.11/site-packages/minio/api.py", line 983, in fput_object

file_size = os.stat(file_path).st_size

^^^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: '/kicad/9c83815c-b571-443e-a185-00ff24c9f8d6/logs/front.svg'

**Comment by fcoury** [comment]
This is the KLE layout:

http://www.keyboard-layout-editor.com/##@_name=60%25%20Tsangan%20-%20Matrix%3B&@=0,0&=0,1&=0,2&=0,3&=0,4&=0,5&=0,6&=0,7&=0,8&=0,9&=0,10&=0,11&=0,12&_w:2%3B&=0,13%3B&@_w:1.5%3B&=1,0&=1,1&=1,2&=1,3&=1,4&=1,5&=1,6&=1,7&=1,8&=1,9&=1,10&=1,11&=1,12&_w:1.5%3B&=1,13%3B&@_w:1.75%3B&=2,0&=2,1&=2,2&=2,3&=2,4&=2,5&=2,6&=2,7&=2,8&=2,9&=2,10&=2,11&_w:2.25%3B&=2,13%3B&@_w:2.25%3B&=3,0&=3,1&=3,2&=3,3&=3,4&=3,5&=3,6&=3,7&=3,8&=3,9&=3,10&_w:1.75%3B&=3,13&=4,13%3B&@_w:1.5%3B&=4,0&=4,1&_w:1.5%3B&=4,2&_w:7%3B&=4,5&_w:1.5%3B&=4,8&=4,9&_w:1.5%3B&=4,11

**Comment by fcoury** [comment]
The problem was having a percentage on the keyboard name! I took it off and it now works fine.

**Comment by adamws** [comment]
thanks for reporting, this will be fixed in v0.6
