### ISSUE TITLE
Almost perfect

### ISSUE THREAD

**Issue by tbaumann** [adamws/keyboard-tools#16]
I struggle with he kicad plugin and the correct annotations. This here could be the perfect workflow, except for one missing feature.

It would be perfect if one could specify the key spacing (Or use choc style spacing when selecting choc footprints)

**Comment by tbaumann** [comment]
Great. Thank you.

Except, key distance is not symmetrical with standard choc spacing. X and Y direction are different. Standard spacing is18x17 mm.

Pretty popular is also 17x17 for ultra tight spacing with CFX keycaps.

**Comment by adamws** [comment]
X/Y is set independently:
![image](https://github.com/user-attachments/assets/9b82bac1-a6b2-4c60-a077-12589441bb99)
![image](https://github.com/user-attachments/assets/71d76a03-84d7-4319-9d71-944f23d446a7)

**Comment by tbaumann** [comment]
:man_facepalming:  Sorry I read the diff on my mobile. Yes I see it now, key_distance is a tuple. Sorry, nevermind.
