### ISSUE TITLE
Runtime Error: Key label invalid

### ISSUE THREAD

**Issue by Jamie-txt** [adamws/keyboard-tools#18]
This layout file worked fine.
[ergoblend-v0.2-compact-LEFT.json](https://github.com/user-attachments/files/17165976/ergoblend-v0.2-compact-LEFT.json)

But the right side layout seems to cause an error.
[ergoblend-v0.2-compact-RIGHT.json](https://github.com/user-attachments/files/17166004/ergoblend-v0.2-compact-RIGHT.json)

![error_kbdtools](https://github.com/user-attachments/assets/cef9b80a-3e67-4ff3-b8a7-cd4439caf4e9)

**Comment by adamws** [comment]
Indeed, something is broken. will take a look some time soon

**Comment by adamws** [comment]
Fixed with 7be6f17fe46d5a2c4390fc523cd1569a4f206cdd
Deployed to https://keyboard-tools.xyz/ in version v0.9
