### ISSUE TITLE
Routing algorithm for keyswitch-kicad-library

### ISSUE THREAD

**Issue by perigoso** [adamws/keyboard-tools#2]
> routing algorithm doesn't work for Alps & MX/Alps Hybrid when Switch_Keyboard in use, see this issue

The [issue](https://github.com/perigoso/keyswitch-kicad-library/issues/4) referenced has been fixed, so I believe this one is fixed too.

**Comment by adamws** [comment]
confirming. Issue not mentioned in docs anymore. Thanks a lot!
