### ISSUE TITLE
Server runs out of space

### ISSUE THREAD

**Issue by goatgitt** [adamws/keyboard-tools#4]
Bad request. MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

**Comment by adamws** [comment]
Server run out of space. I removed old data by hand so it's working again but proper fix still needed. 
Note to myself: something is wrong with s3 config.

**Comment by goatgitt** [comment]
I've got another error:
{ "exc_message": "Traceback (most recent call last):\n File \"/kicad/src/tasks.py\", line 69, in generate_kicad_project\n log_path = kicad.new_pcb(task_id, task_request, __update_percentage)\nException: Generate netlist failed\n", "exc_type": "Exception" }

**Comment by adamws** [comment]
There has to be something wrong with file you are uploading. I can take a look if you don't mind sharing.

**Comment by goatgitt** [comment]
there is layout on my github gist : https://gist.github.com/goatgitt/3cea00678c6a454bb338f5836469b9d1

**Comment by TrUsT-101** [comment]
Hi there! Sorry to be a pain, but I was really hoping to use this on keyboard-tools.xyz, but am getting the original error message posted above. Any chance you could please clear the old data again? It's exactly the thing I've been searching for and I fear I'm not clever enough to implement a workaround myself..!

**Comment by adamws** [comment]
@TrUsT-101 Hi, I freed some space, should work in the near future.

**Comment by TrUsT-101** [comment]
> @TrUsT-101 Hi, I freed some space, should work in the near future.

Thank you very much, that is very kind of you! :)
